Repository alfredo203/opt_pyFE, pull requests merged in 2024-10, with the labels that each got.

#1 Modificar readme
  AUTHORS.rst
  CONTRIBUTING.rst
  README.md
  README.rst
  pyproject.toml
Labels: documentation

#3 Funciones de Var y CVar
  src/opt_pyFE/Paquete_AnalisisRiesgo.py
Labels: feature

#2 Create Empaquetado{Gab].py
  src/opt_pyFE/EmpaquetadoGab.py
Labels: enhancement

#8 Estandarización código
  src/opt_pyFE/opt_pyFE estandarizado.py
Labels: documentation
